name: Terraform Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive
